### PR TITLE
Various fixes

### LINKED ISSUE #2: Does not work after first build
Following the recipe from https://dev.to/duffleit/bridging-the-gap-between-gatsby-and-open-graph-images-52gh and running it in `createPage` API produces following error:

```
"gatsby-plugin-open-graph-images" threw an error while running the onPostBuild lifecycle:

ENOENT: no such file or directory, unlink 'public/__generated/og-images5e5da90b-fa11-57c1-b3a1-ee3786ff2120.png/index.html'

  16 | exports.onPostBuild = async ({ cache }) => {
  17 |   const jobDefinitions = await imageGenerationJobCache.getAll(cache);
> 18 |   await generateOgImages(jobDefinitions);
     |   ^
  19 | };
  20 | 

File: node_modules/gatsby-plugin-open-graph-images/gatsby-node.js:18:3



  Error: ENOENT: no such file or directory, unlink 'public/__generated/og-images5e5da90b-fa11-57c1-b3a1-ee3786ff2120.png/index.html'
  
  - generator.js:22 exports.generateOgImages
    [danielamulle.at]/[gatsby-plugin-open-graph-images]/src/generator.js:22:8
  
  - gatsby-node.js:18 async Object.exports.onPostBuild
    [danielamulle.at]/[gatsby-plugin-open-graph-images]/gatsby-node.js:18:3
```

### PR DESCRIPTION
**Pull request by okonet**
Fixes #2 and another issue I encountered...

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ const { join } = require("path");
 const { config } = require("./src/config");
 
 exports.createOpenGraphImage = (createPage, options) => {
+  config.init(options)
```
Comment (williamwgant) [inline index.js:5]: This fixes #7 in my local environment.

**Comment by neurosnap** [comment]
Because these changes are critical for this plugin to function and there have been no responses from the author, I have incorporated these changes in a forked npm package: 
- https://www.npmjs.com/package/gatsby-plugin-ogi
- https://github.com/neurosnap/gatsby-plugin-ogi

I hope this is viewed in good faith, I do not intend to siphon users from this project, but I needed these fixes and I figured others would face similar frustrations.
